---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
 
- name: Install required Packages for RedHat
  yum: name={{ item }} state=installed
  with_items: "{{packages}}"
  when: ansible_os_family == 'RedHat'


- name: Install required Packages for Ubuntu
  apt: name={{ item }} state=installed update_cache=yes
  with_items: "{{packages}}"
  environment: env
  when: ansible_os_family == 'Debian'
