packages:  
  - epel-release
  - gcc
  - gcc-c++
  - python-virtualenv
  - python-pip
  - python-devel
  - libffi-devel
  - openssl-devel
  - libyaml-devel
  - sshpass
  - vim-enhanced
  - git
  - curl
  - unzip
  - tar
  - wget
  - openssl
  - ntp
  - postgresql
  - postgresql-jdbc
  - postgresql-server
  - MySQL-python
  - mysql-connector-java
  - MySQL-python
  - mysql-connector-java
